### ISSUE TITLE
After Install module showing error

### ISSUE THREAD

**Issue by matinict** [thinkoverit/sms-magento2#1]
After Install module showing error admin Panel not working
Invalid Document Element 'resource': The attribute 'title' is required but missing. Line: 5 Element 'resource': The attribute 'title' is required but missing. Line: 10 Element 'resource': The attribute 'title' is required but missing. Line: 11 Element 'resource': The attribute 'title' is required but missing. Line: 12

**Comment by thinkoverit** [comment]
Please update the module files. acl updated as per latest updates..

**Comment by matinict** [comment]
Update Module also Show Error in admin Panel:
1 exception(s):
Exception #0 (LogicException): Could not create an acl object: Invalid Document 
Element 'resource': The attribute 'title' is required but missing.
Line: 12


Exception #0 (LogicException): Could not create an acl object: Invalid Document 
Element 'resource': The attribute 'title' is required but missing.
Line: 12

**Comment by thinkoverit** [comment]
What version of Magento are you working on?
With Magneto version 2.1.3 module is working fine. we couldn't reproduce error ..

**Comment by matinict** [comment]
my magento version magento 2.2 ,

I need to upgrade magento 1.x to 2x my script https://github.com/SSLWireless/MagentoSMS u can help?

**Comment by thinkoverit** [comment]
Works perfectly with 2.2 Magento. SMS module does get installed and all menus are visible too. Please try disabling 3rd party modules to locate the module giving issues.

Finally you just need to update Default Module helper file  function "sendSms" to use SSLWireless API to send SMS.

**Comment by matinict** [comment]
Module  installed  successfully in my xampp localhost, admin interface also working properly, 
But I add my api UserID & Pass also change API url From Data 

MY API RAW CODE BELOW:[Hope u be help me ]

	$user ="testuser"; 
	$pass = "1234"; 
	$sid = "TEST"

	$msisdn2='01747544555';
	$msisdn='01717676441';
	$sms ='Congrats test1! You have successfully made order ****.Test sms  Thank You. @DICPAL';		
	

	$url="http://sms.sslwireless.com/pushapi/dynamic/server.php";
	$unique_id_1=uniqid();
	$unique_id_2=uniqid();
	
	$param="user=$user&pass=$pass&sid=$sid&";	
	$sms="sms[0][0]=$msisdn&sms[0][1]=".urlencode($sms)."&sms[0][2]=".$unique_id_1."&sms[1][0]=$msisdn2&sms[1][1]=".urlencode($sms)."&sms[1][2]=".$unique_id_2."";

	$data=$param.$sms.$sid;	
	$crl = curl_init();
	curl_setopt($crl,CURLOPT_SSL_VERIFYPEER,FALSE);
	curl_setopt($crl,CURLOPT_SSL_VERIFYHOST,2);
	curl_setopt($crl,CURLOPT_URL,$url); 
	curl_setopt($crl,CURLOPT_HEADER,0);
	curl_setopt($crl,CURLOPT_RETURNTRANSFER,1);
	curl_setopt($crl,CURLOPT_POST,1);
	curl_setopt($crl,CURLOPT_POSTFIELDS,$data); 
	$response = curl_exec($crl);
	curl_close($crl);
	
	echo $response;

**Comment by thinkoverit** [comment]
Good to know. You need to make sure SSLWireless API is called with right parameters ..
